[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Andy Caldwell <andrew.caldwell@metaswitch.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
recap = "0.1.1"
serde = "1.0.118"
itertools = "0.9.0"
